-- both test users have the password "password"

-- INSERT INTO users (username, password, first_name, last_name)
-- VALUES ('testuser',
--         '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
--         'Test',
--         'User');

-- INSERT INTO companies (handle,
--                        career_page,
--                        username)
-- VALUES ('Google', 'https://careers.google.com/jobs/results/', 'testuser'),
--         ('Chase', 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1002/requisitions?keyword=software+engineer', 'testuser');


-- INSERT INTO jobs (title,
--                   company_handle,
--                   username)
-- VALUES ('Software Engineer', 'google', 'testuser');

INSERT INTO companies (handle,
                       career_page)
VALUES ('540','https://540.co/jobs.html'),
('360dialog','https://angel.co/company/360dialog/jobs'),
('ActionIQ','https://www.actioniq.com/careers/open-positions/'),
('Adyen','https://careers.adyen.com/'),
('Aetion','https://aetion.com/company/careers/'),
('Age Bold','https://agebold.com/careers/'),
('Agora','https://www.agora.io/en/careers/open-positions/'),
('Agrippa','https://angel.co/company/agrippa-logo'),
('Air','https://jobs-airdc.icims.com/jobs/intro?mobile=false&width=998&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240'),
('Alexandria Labs','https://phe.tbe.taleo.net/phe03/ats/careers/v2/searchResults?org=ALEXANDRIARE&cws=40'),
('Alloy','https://www.alloy.com/about/jobs'),
('Alma','https://www.linkedin.com/company/withalma/jobs/'),
('Andela','https://boards.greenhouse.io/andela'),
('Apple','https://jobs.apple.com/en-us/search?location=united-states-USA'),
('AppWrite','https://appwrite.io/company/careers#openings'),
('Aquicore','https://jobs.lever.co/aquicore'),
('Artera','https://artera.applicantstack.com/x/openings'),
('Artium','https://www.atriumstaff.com/job-seekers/?function%5B%5D=379'),
('Ascendion','https://jobs.ascension.org/careers-home/jobs?keywords=software%20engineer'),
('AssemblyAi','https://www.assemblyai.com/careers'),
('Asvatthi','https://angel.co/company/asvatthi-1'),
('Athena Advisory','https://athenaconsultinggroup.com/about/careers/'),
('Athletic','https://jobs.lever.co/theathletic'),
('Atlassian','https://www.atlassian.com/ko/company/careers/all-jobs'),
('Authentise','https://www.authentise.com/company-overview'),
('Ava Accessibility','https://angel.co/company/ava-me'),
('Ava Labs','https://boards.greenhouse.io/avalabs'),
('Axio','https://axio.com/careers/'),
('Ballooning Nest Eggs, Inc','https://www.ballooningnesteggs.com/careers'),
('Bask Health','https://www.bask.bio/careers'),
('Bellhop','https://jobs.lever.co/bellhops'),
('BioRender','https://jobs.lever.co/biorender'),
('Bluelight Consulting','https://jobs.lever.co/bluelightconsulting'),
('Broadridge','https://broadridge.wd5.myworkdayjobs.com/Careers'),
('Caesar','https://edmn.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1'),
('CardFlight','https://boards.greenhouse.io/cardflight'),
('Carrot Fertility','https://www.get-carrot.com/company/careers/open-roles'),
('Cascade.io','https://www.cascade.io/jobs/back-end-engineer'),
('Certik','https://jobs.lever.co/certik/'),
('Chainlink Labs','https://chainlinklabs.com/jobs'),
('Champify','https://www.champify.io/careers/full-stack-engineer'),
('Chronograph','https://www.chronograph.pe/careers/#jobs'),
('Cisco','https://www.cisco.com/c/en/us/about/careers.html#~job-areas'),
('Cisco Meraki','https://meraki.cisco.com/job-search/'),
('Clever','https://clever.com/about/careers#career-listing'),
('ClickTime','https://www.clicktime.com/company/careers#2'),
('CM Group','https://cmgcompany.com/careers/'),
('CoinAlpha','https://angel.co/company/coinalpha'),
('Collbra','https://www.collibra.com/us/en/company/careers#find-jobs'),
('Column','https://www.column.us/careers/'),
('Commonwealth','https://www.commonwealth.com/careers/roles'),
('Confidential','https://careers.smartrecruiters.com/Confidential33'),
('Confirm','https://angel.co/company/confirmhr/jobs'),
('Corvus Insurance','https://www.corvusinsurance.com/careers-at-corvus#section-3'),
('Craft.co','https://enterprise.craft.co/careers#Jobs'),
('CSI Companies','https://jobs.csicompanies.com/'),
('Cultivate','https://cultivateteam.hire.trakstar.com/'),
('CVS Health','https://jobs.cvshealth.com/job-search-results/?keyword=Corporate'),
('CyberCoders','https://www.cybercoders.com/careers/'),
('Cypris','https://angel.co/company/cypris/jobs'),
('Datadog','https://careers.datadoghq.com/engineering/'),
('Datatron Technologies','https://datatron.betterteam.com/'),
('Decentral','https://cryptocurrencyjobs.co/startups/decentral-games/'),
('DeepNFTValue','https://www.f6s.com/jobs/53159/deepnft-value/backend-engineer-distributed-us'),
('DeepWalk','https://angel.co/company/deepwalk'),
('Deteremined AI','https://careers.hpe.com/us/en/search-results?keywords=%22Determined%20AI%22'),
('Disney','https://jobs.disneycareers.com/search-jobs'),
('Donut','https://jobs.lever.co/donut'),
('DoubleLoop','https://angel.co/company/doubleloopapp'),
('DreamHost','https://www.dreamhost.com/careers/'),
('Drift Labs','https://www.drift.com/about/careers/#openings'),
('Dun & Bradstreet','https://www.dnb.com/about-us/careers-and-people/careers.html'),
('DVx Ventures','https://dvxventures.applytojob.com/'),
('EcoCart','https://ecocart.io/careers/'),
('Edacious','https://jobs.lever.co/edacious'),
('Edward Jones','https://careers.edwardjones.com/'),
('Eight Sleep','https://jobs.ashbyhq.com/eightsleep'),
('Engine','https://enginecareers.com/join-us'),
('Enlock','https://jobs.lever.co/biorender'),
('ESG Impact','https://jobs.lever.co/esg-impact'),
('Etalon','https://angel.co/company/etalon-dx?utm_campaign=startup_share&utm_content=startup_share_module&utm_medium=social&utm_source=facebook&utm_term=etalon-dx'),
('Etsy','https://careers.etsy.com/global/en/c/engineering-jobs'),
('Facet','https://facet.ai/jobs'),
('Farmers Dog','https://www.thefarmersdog.com/careers#open-positions'),
('Fasta','https://angel.co/company/fasta-ai-1'),
('Fellow','https://jobs.lever.co/fellowproducts'),
('Fiserv','https://www.careers.fiserv.com/search-jobs'),
('Flawless','https://flawlessrecruit.pinpointhq.com/#js-careers-jobs-block'),
('Flox','https://floxdev.com/careers'),
('Flyreel','https://apply.workable.com/flyreel/?lng=en'),
('Foot Locker','https://hub-na-en-corp-footlocker.icims.com/jobs/search?hashed=-435683037&mobile=false&width=1030&height=500&bga=true&needsRedirect=false&jan1offset=-360&jun1offset=-300'),
('Forbes','https://boards.greenhouse.io/forbes/'),
('Fortue','https://boards.greenhouse.io/fortune/'),
('Fourkites','https://www.fourkites.com/current-openings/'),
('Frame','https://www.linkedin.com/company/frame-denim/mycompany/'),
('FullStack Labs','https://jobs.lever.co/fullstacklabs/'),
('Gantry','https://jobs.jobvite.com/gantry/jobs'),
('Gemini','https://www.gemini.com/careers'),
('General Motors','https://search-careers.gm.com/en/jobs/'),
('Genius Sports','https://www.geniussports.com/careers/'),
('Gordian','https://careers.fortive.com/search-results?keywords=software%20engineer'),
('Grammarly','https://www.grammarly.com/jobs/openings'),
('Gridwise','https://gridwise.io/careers/'),
('Guidepoint','https://www.guidepoint.com/careers/'),
('Hagerty','https://hagerty.wd5.myworkdayjobs.com/hagerty'),
('Halian','https://halian.com/portal/jobs/1300106/Freelance-Test-Manager-%2F-Coordinator----Brussels---Initial-12-Months-contract?date=anyTime&jobType=all&salary=all&sort=mostRecent'),
('Halo AI','https://angel.co/company/halo-ai-2/jobs'),
('Hardfin','https://angel.co/company/hardfin/jobs'),
('HeadsUp','https://angel.co/company/headsupdata'),
('Headway','https://headway.co/careers#open-roles'),
('HealthVerity','https://jobs.lever.co/healthverity'),
('Hearth','https://www.gethearth.com/careers/'),
('Height','https://angel.co/company/height/jobs'),
('High Tech Genesis','https://jobs.hightechgenesis.com/'),
('him & hers','https://boards.greenhouse.io/himshers'),
('Hippo Education','https://home.hippoed.com/careers#current-openings'),
('Housecall Pro','https://www.housecallpro.com/careers/#join-us'),
('HSM','https://recruiting.ultipro.com/HIC1002HSMC/JobBoard/ee60fb00-907f-4b73-99da-216918328f53/?q=&o=postedDateDesc&w=&wc=&we=&wpst='),
('Hudl','https://www.hudl.com/jobs/search'),
('Impiricus','https://angel.co/company/impiricus-2/jobs'),
('Informa Tech','https://join.smartrecruiters.com/InformaGroupPlc/49c3c005-012c-4930-81e3-150fb168ff96-registration-form'),
('Insight Global','https://jobs.insightglobal.com/?_gl=1*1ufdpkx*_ga*NDEyMjgzMzA3LjE2NzY0OTE5MTc.*_ga_CD4GGVP4P1*MTY3NjQ5MTkxNi4xLjAuMTY3NjQ5MTkxNi42MC4wLjA.&_ga=2.227799901.1535011147.1676491917-412283307.1676491917'),
('Internet Brands','https://jobs.jobvite.com/internetbrands'),
('Isometric Technologies','https://www.iso.io/about/careers/'),
('Jane','https://jobs.lever.co/jane'),
('Jangle','https://jobs.jungle.ai/'),
('JCrew','https://jobs.jcrew.com/JCrew'),
('John Deer','https://careers.deere.com/careers?query=internship&pid=137452516816&domain=johndeere.com&triggerGoButton=true'),
('JOON','https://www.joon.com/job'),
('JP Morgan','https://careers.jpmorgan.com/US/en/home'),
('Julep Wellness','https://angel.co/company/julep-wellness'),
('Jurat','https://www.linkedin.com/company/jurat/'),
('Kado','https://angel.co/company/kado-2/jobs'),
('Kinship','https://boards.greenhouse.io/kinship'),
('Komodo Health','https://www.komodohealth.com/careers/current-job-openings'),
('Lazarus','https://lazarus.gg/careers/'),
('lexie.ai','https://angel.co/company/lexie-ai'),
('Liberty Mutual Insurance','https://jobs.libertymutualgroup.com/search-jobs/?keyword=software%20engineer'),
('Lime','https://jobs.lever.co/lime'),
('Live Chair Health','https://www.livechair.co/careers'),
('Logseq','https://blog.logseq.com/jobs/'),
('Loom','https://www.loom.com/careers#positions'),
('Loyal','https://loyalhealth.com/careers/'),
('Lukka','https://lukka.tech/careers/'),
('Macquarie Group','https://www.careers.macquarie.com/en/listing/'),
('Magic','https://getmagic.com/careers/'),
('making-millets','https://www.jobs-milletmountaingroup.com/apply-directly/'),
('maven','https://www.mavenclinic.com/careers#hybrid-work-banner'),
('Medallion','https://medallion.co/about-medallion/careers'),
('Messari','https://messari.io/careers#opportunities'),
('MetaMask','https://cryptocurrencyjobs.co/startups/metamask/'),
('MetLife','https://jobs.metlife.com/go/Corporate-Jobs/2763000/'),
('Metronome','https://jobs.lever.co/getmetronome'),
('Michael Page','michaelpage.com/job-search'),
('MindCloud','https://angel.co/company/mindcloud-1/jobs'),
('Mintlify','https://jobs.ashbyhq.com/Mintlify'),
('Modyfi','https://angel.co/company/modyfi'),
('Mount Sinai Health System','https://jobs.sinaichicago.org/'),
('Multiverse','https://www.multiverse.io/en-US/careers#job-list'),
('MYM','https://careers.mgmresorts.com/global/en'),
('Myna Swap','https://apply.workable.com/myna-swap-llc/?lng=en'),
('Netcapital','https://netcapital.com/careers'),
('Netflix','https://jobs.netflix.com/'),
('NetSuite','https://www.oracle.com/careers/opportunities/netsuite/'),
('NuBinary','https://nubinary.com/join-our-team'),
('Numerade','https://www.numerade.com/careers/'),
('NY Times','https://nytimes.wd5.myworkdayjobs.com/NYT'),
('olive','https://apply.workable.com/olive/'),
('Oncue','https://oncueexpress.com/careers/'),
('Ontra','https://www.ontra.ai/careers/'),
('OpenFin','https://www.openfin.co/careers/'),
('Ostium','https://www.ostiumtalent.com/current-jobs/'),
('Paladin','https://www.joinpaladin.com/jobs/'),
('Paleo','https://paleo.technology/careers#openingPositions'),
('Particle','https://www.particle.io/careers/#job-listings'),
('Patreon','https://www.patreon.com/careers'),
('Pattern Financial','https://pattern.wd1.myworkdayjobs.com/en-US/Pattern_Careers'),
('Pave','https://boards.greenhouse.io/paveakatroveinformationtechnologies'),
('Paycor','https://www.paycor.com/company/careers/available-positions/'),
('Paylocity','https://www.paylocity.com/careers/'),
('Photon Commerce','https://www.photoncommerce.com/jobs'),
('Pillar','https://pillarcareers-beitzelpillar.icims.com/jobs/intro?hashed=-435713783&mobile=false&width=703&height=500&bga=true&needsRedirect=false&jan1offset=-360&jun1offset=-300'),
('Place Exchange','https://www.placeexchange.com/join-our-team'),
('Plaid','https://plaid.com/careers/'),
('PriceLabs','https://pricelabs.freshteam.com/jobs'),
('QuantAQ','https://jobs.ashbyhq.com/quant-aq'),
('Quorum','https://www.quorum.us/about/careers/#available-positions'),
('re:collect, AI','https://re-collect.notion.site/Jobs-re-collect-96ffc580d08040518c19591b96937949'),
('Recurate','https://angel.co/company/recurate/jobs'),
('Red Hat','https://careers-redhat.icims.com/jobs/search?mobile=false&width=1140&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240'),
('Relief App','https://www.relief.app/careers'),
('Replicated','https://www.replicated.com/careers#positions'),
('Resourcely','https://jobs.ashbyhq.com/Resourcely'),
('Retain.ai','https://retain.ai/careers/'),
('Revel','https://gorevel.com/careers'),
('Rhombus','https://www.rhombus.com/careers/'),
('Ribbon','https://www.ribbonhome.com/careers#jobsContainer'),
('Ripple','https://ripple.com/careers/all-jobs/'),
('Rosetta Analytics','https://angelo-calvello.squarespace.com/careers-1'),
('Safara','https://www.google.com/search?q=Safara+careers&oq=Safara+careers&aqs=chrome..69i57j0i10i512j0i390l3.1263j0j4&sourceid=chrome&ie=UTF-8'),
('Sapling Intelligence','https://www.ycombinator.com/companies/sapling-ai/jobs'),
('Seed','https://seed.com/join-us/'),
('SideQuestVR','https://jobs.lever.co/sidequest'),
('Sismic','https://seismic.com/careers/job-listings/'),
('SJ Technologies','https://www.sjtechcorp.com/careers/'),
('SmartPass','https://angel.co/company/smartpassco'),
('Social Snowball','https://angel.co/company/social-snowball'),
('Sorare','https://sorare.com/careers#jobs'),
('SphereOne','https://www.google.com/search?q=SphereOne+career&oq=SphereOne+career&aqs=chrome..69i57j33i160l3.1406j0j4&sourceid=chrome&ie=UTF-8'),
('Sprinter Health','https://jobs.lever.co/SprinterHealth'),
('Sprout Social','https://sproutsocial.com/careers/open-positions/'),
('Square Roots','https://www.squarerootsgrow.com/careers#career-opportunities'),
('Squarespace','https://www.squarespace.com/about/careers'),
('Standard','https://standard.wd1.myworkdayjobs.com/Search'),
('StarTree','https://startree.ai/careers'),
('Status','https://jobs.status.im/'),
('Stems Labs','https://angel.co/company/stemslabs'),
('Step','https://step.com/careers'),
('STL Digital','https://stldigital.tech/about-us/careers/'),
('StockX','https://careers.stockx.com/'),
('Stripe','https://stripe.com/jobs/search'),
('Sudowrite','https://angel.co/company/sudowrite'),
('Swiftlane','https://www.swiftlane.com/careers/'),
('Syergy Interactive','https://www.linkedin.com/jobs/search/?locationId=OTHERS%2Eworldwide&f_C=1087408'),
('Tab for a Cause','https://tab.gladly.io/jobs/'),
('TDA Creative','https://www.tdacreative.com/jobs/'),
('Temelpa','https://triplebyte.com/company/public/temelpa-holdings-incs'),
('Theia Studios','https://theiastudios.io/careers/'),
('Tractable','https://tractable.ai/en/jobs'),
('TribeHealth','https://angel.co/company/tribehealth/jobs'),
('Trimble','https://trimblecareers.trimble.com/careers'),
('Truffle Security CO','https://trufflesecurity.com/careers/'),
('Trunk','https://trunk.io/jobs'),
('Trustworty','https://angel.co/company/trustworthyco'),
('Twilio','https://boards.greenhouse.io/twilio'),
('Usage AI','https://usage.ai/careers'),
('VDart','https://www.vdart.com/internal-vacancies/'),
('Vendelux','https://vendelux.com/careers/'),
('Verint','https://fa-epcb-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX'),
('VideoAmp','https://videoamp.com/jobs/'),
('Violet','https://www.joinviolet.com/careers'),
('Viva Translate','https://angel.co/company/viva-translate'),
('Voyage SMS','https://www.voyagesms.com/careers'),
('Walgreens','https://jobs.walgreens.com/en'),
('Wepay','https://go.wepay.com/careers-openings/'),
('Wincast','https://angel.co/company/wincast'),
('Wingz','https://apply.workable.com/wingz/'),
('Worko','https://work.co/careers/'),
('X1 Card','https://jobs.lever.co/x1creditcard/'),
('Xander','https://www.xandertalent.com/careers/'),
('Xpanxion','https://www.xpanxion.com/about/careers/'),
('Yahoo','https://www.yahooinc.com/careers/'),
('Yesware','https://www.vendasta.com/company/careers/'),
('Zillow','https://career.zillowgroup.com/careers'),
('Zoom','https://careers.zoom.us/jobs/search'),
('Zora','https://boards.greenhouse.io/zora')